import Head from 'next/head'
import { getUsers } from '@/store/hooks/user'

export default function Home() {
  getUsers()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>表示</main>
    </>
  )
}
